### ISSUE TITLE
Getting issue while implementing GSN in our GEM NFT contract.

### ISSUE THREAD

**Issue by wscf-development** [Charged-Particles/charged-particles-universe#42]
Hi Team,

We are creating the NFT contract as GEM which will be key to Supraorbs Casino Games (https://www.supraorbs.com). We have successfully compiled it through hardhat, deployed it to the Kovan network, and got whitelisted as well. We are unable to interact with it as GSN implementation is missing from the contract. So, We have implemented the same similar to the Proton contract. The updated contract is also got compiled successfully using hardhat but we are getting the issue while trying to deploy it on the Kovan network. Please find the attached contract code and issue details below for your reference. Kindly verify and suggest what can be done here and let us know if you need any more information.

[Gem.sol.zip](https://github.com/Charged-Particles/charged-particles-universe/files/6847072/Gem.sol.zip)

Hardhat compilation logs:

yarn start
yarn run v1.22.10
$ hardhat node --port 8545
Nothing to compile

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Supraorbs Casino - Contract Deployment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Using Network:  Hardhat
  Using Accounts:
  - Deployer:           0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  - Owner:              0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  - Trusted Forwarder:  0x70997970C51812dc3A010C7d01b50e0d17dc79C8
 
  Deploying Supraorbs Casino...

  Contract Deployments Complete!

  Contracts:
  - SupraorbsCasino:          0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
     - Gas Cost:       0.005321301 ETH

  Contract Deployment Data saved to "deployments" directory.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Supraorbs Casino: Gem - Contract Deployment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Using Network:  Hardhat
  Using Accounts:
  - Deployer:           0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  - Owner:              0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  - Trusted Forwarder:  0x70997970C51812dc3A010C7d01b50e0d17dc79C8
 
  Deploying Gem NFT...

  Contract Deployments Complete!

  Contracts:
  - Gem:          0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
     - Gas Cost:       0.005592644 ETH

  Contract Deployment Data saved to "deployments" directory.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Supraorbs Casino - Contract Initialization
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Using Network:  Hardhat
  Using Accounts:
  - Deployer:           0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  - Owner:              0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  - Trusted Forwarder:  0x70997970C51812dc3A010C7d01b50e0d17dc79C8
 
  Loading Supraorbs Casino from:  0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
  Loading Gem from:  0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9


  - [TX-1-a] Supraorbs Casino: Registering Gem at: 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
  - [TX-2-b] Gem: Registering ChargedState
  - [TX-2-c] Gem: Registering ChargedSettings
  - [TX-2-d] Gem: Registering ChargedParticles

  Contract Initialization Complete!

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Kovan deployment logs:

yarn deploy --network kovan
yarn run v1.22.10
$ yarn clean-test && hardhat deploy --network kovan
$ rm -rf abis .openzeppelin/${npm_config_network:-'unknown-31337'}.json deployments/${npm_config_network:-hardhat}/*.json test-results.xml
Nothing to compile

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Supraorbs Casino - Contract Deployment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Using Network:  Kovan
  Using Accounts:
  - Deployer:           0x0D8546187C10729260854444Cd28aA76EDacFE51
  - Owner:              0x0D8546187C10729260854444Cd28aA76EDacFE51
  - Trusted Forwarder:  0x0C8ce8eF948b41819138a5d27c160340a7991Dbd
 
  Deploying Supraorbs Casino...

  Contract Deployments Complete!

  Contracts:
  - SupraorbsCasino:          0x78f3E1c99d9c0D2f5f473696D20a1bf05Bb93E9b
     - Gas Cost:       0.05321301 ETH

  Contract Deployment Data saved to "deployments" directory.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Supraorbs Casino: Gem - Contract Deployment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Using Network:  Kovan
  Using Accounts:
  - Deployer:           0x0D8546187C10729260854444Cd28aA76EDacFE51
  - Owner:              0x0D8546187C10729260854444Cd28aA76EDacFE51
  - Trusted Forwarder:  0x0C8ce8eF948b41819138a5d27c160340a7991Dbd
 
  Deploying Gem NFT...
An unexpected error occurred:

Error: ERROR processing /Users/nigamsaini/Development/GitHub/Blockchain/Supraorbs-Contracts-ETH/deploy/1_gem.js:
ProviderError: The execution failed due to an exception.
    at HttpProvider.request (/Users/nigamsaini/Development/GitHub/Blockchain/Supraorbs-Contracts-ETH/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at HDWalletProvider.request (/Users/nigamsaini/Development/GitHub/Blockchain/Supraorbs-Contracts-ETH/node_modules/hardhat/src/internal/core/providers/accounts.ts:152:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at EthersProviderWrapper.send (/Users/nigamsaini/Development/GitHub/Blockchain/Supraorbs-Contracts-ETH/node_modules/hardhat-deploy-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
    at DeploymentsManager.executeDeployScripts (/Users/nigamsaini/Development/GitHub/Blockchain/Supraorbs-Contracts-ETH/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1052:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by wscf-development** [comment]
The issue was due to the exceeded size of the contract. It's resolved now.
